### ISSUE TITLE
Should we add libhubbub?

### ISSUE THREAD

**Issue by RReverser** [lexborisov/benchmark-html-persers#1]
Great work on myhtml and benchmarks. I wondered if you looked into http://www.netsurf-browser.org/projects/hubbub/ and whether you tried to compare it with others in this benchmark / whether it would make sense to.

libhubbub is also written in pure C, claims to be HTML5 compliant and good for low-end machines, so would be interesting to see it in such comparison.

**Comment by lexborisov** [comment]
Hi!
Thanks! 

This is not good:
Hubbub also requires the following libraries to be installed:
    + An iconv implementation (e.g. libiconv)
    + LibParserUtils -- see below for further information
    + JSON-C (for the testcases) -- see below for further information

but i am look to him

**Comment by RReverser** [comment]
LibParserUtils is just one of their own helper deps - it's all statically linked into a one lib.
JSON-C, as the page claims, is just for the testcases - not needed for actual usage.

iconv is required for supporting external encodings, can be built without it if running only UTF-8. Anyway, this one shouldn't be a big deal as is easily installable on all platforms.

**Comment by lexborisov** [comment]
I can not build him. He gives a lot of errors. I install buildsystem (/opt/local/share/netsurf-buildsystem) but, he not compile. Oh, tries later

**Comment by RReverser** [comment]
Weird. Built fine myself from the first try, both on Mac and Debian.

**Comment by lexborisov** [comment]
from http://download.netsurf-browser.org/libs/releases/libhubbub-0.3.3-src.tar.gz

Darwin MBP-Alexander 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix

I deal with it tomorrow

**Comment by lexborisov** [comment]
libhubbub && libdom:
    Overall time: 7.10649;
    Memory at the beginning: 1110016;
    Memory at the end: 804683776

libhubbub:
    Overall time: 2.23302;
    Memory at the beginning: 1110016;
    Memory at the end: 13430784

**Comment by RReverser** [comment]
Nice, thanks. As for the LibDOM - it's full implementation of actual DOM APIs for the browser, so I think it's irrelevant here, although still interesting for the comparison. Would you add results to the article?

**Comment by lexborisov** [comment]
Added
