### ISSUE TITLE
Please add single-threaded MyHTML to the article summary

### ISSUE THREAD

**Issue by RReverser** [lexborisov/benchmark-html-persers#2]
In the article - http://lexborisov.github.io/benchmark-html-persers/ - there is a summary section about "Ex vivo test result. Running all (466) pages in 1 process" which contains only multithreaded mode of MyHTML compared with [single-threaded] Gumbo and HTML5Ever parsers, even though all the graphs have both versions of MyHTML usage.

It would be [much more] interesting to see summary comparison of single-threaded versions of each parser, as in many cases parsers will be called for tasks in parallel as part of threads created and managed by some external parent scheduler.

**Comment by lexborisov** [comment]
I somehow forgot about it. Added
If page not updated add ?5656 to url: http://lexborisov.github.io/benchmark-html-persers/?5656

**Comment by RReverser** [comment]
Awesome, thanks!
