### ISSUE TITLE
Typo in repository name

### ISSUE THREAD

**Issue by ligurio** [lexborisov/benchmark-html-persers#3]
Thanks for benchmarks!
there is a typo ('persers') in repository name and it is confusing a bit.

**Comment by lexborisov** [comment]
@ligurio 

Thank you, yes, but I think it's not that important :)
Changing the name of the repository is not a good idea.

**Comment by ligurio** [comment]
Github sets redirects automatically after repository rename.

**Comment by lexborisov** [comment]
@ligurio 

Great, changed the name.

Thanks for the report!
